Polling2/pollster/pages/urls.py
# Import the path from django.urls.
from django.urls import path
# Import the views
from . import views

# set the url pattern
urlpatterns = [
    # setting up a path for the index
    # first param empty sets to '/'
    # second param is the view
    # third param is the name of the view
    path('', views.index, name='index'),
]

Polling2/pollster/polls/urls.py
# Import the path from django.urls.
from django.urls import path
# Import the views
from . import views

# name the app
app_name = 'polls'
# set the url pattern
urlpatterns = [
    # setting up a path for the index
    # first param empty sets to '/'
    # second param is the view
    # third param is the name of the view
    path('', views.index, name='index'),
    # first is the url parameter
    # second is the view
    # thrid is the name
    path('<int:question_id>/', views.detail, name='detail'),
    # first is the url parameter
    # second is the view
    # third is the name
    path('<int:question_id>/results/', views.results, name='results'),
    # first is the url parameter
    # second is the view
    # third is the name
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Polling2/pollster/pollster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

Polling2/pollster/pages/models.py
from django.db import models

# Create your models here.

Polling2/pollster/polls/models.py
from django.db import models

class Question(models.Model):
    # Question_text which is the question itself
    question_text = models.CharField(max_length=200)
    # pub_date is the date the question was published
    pub_date = models.DateTimeField('date published')
    # defining string method which returns the question text
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    # ForeignKey for a relation between Question and Choice 
    # #with cascade because if there is no question there is no reason to it's have choices
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # Choice_text which is the choice itself
    choice_text = models.CharField(max_length=200)
    # votes is the number of votes the choice has
    votes = models.IntegerField(default=0)
    # defining string method which returns the choice text
    def __str__(self):
        return self.choice_text

Polling2/pollster/pages/views.py
from django.shortcuts import render

# define a method which will render a static lading page
def index(request):
    return render(request, 'pages/index.html') 

Polling2/pollster/polls/views.py
from django.http.response import Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

# import the models
from .models import Question, Choice

# Get Questions and display them
def index(request):
    # get a list of questions ordered descending by date per 5
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # pass the list to the template
    context = {'latest_question_list': latest_question_list}
    # render the template
    return render(request, 'polls/index.html',context)

# show a specific question and its choices
def detail(request, question_id):
    try:
        # get the question
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    # return the question
    return render(request, 'polls/detail.html', {'question': question})

# Get question and display results
def results(request, question_id):
    # check db for question or return a 404
    # pk = is via the url parameter
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

# vote for a question
def vote(request, question_id):
    # get the question
    question = get_object_or_404(Question, pk=question_id)
    # get the choice
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Polling2/pollster/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class='container'>
        <div class='row'>
            <div class='col-md-6 m-auto'>
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

Polling2/pollster/templates/pages/index.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock %}
{% block content %}

<div class="card text-center">
    <div class="card-body">
        <h1>Welcome to the poll app</h1>
        <p>This is my first Django app</p>
        <a class="btn btn-dark" href="{% url 'polls:index' %}">View polls</a>
    </div>
</div>
{% endblock %}

Polling2/pollster/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">Home</a>
    </div>  
</nav>

Polling2/pollster/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %}
Details
{% endblock %}
{% block content %}
<a class="btn btn-secondary btn-sm mb3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text}}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input
        type="radio"
        name="choice"
        class="form-check-input"
        id="choice {{ forloop.counter}}"
        value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter}}">{{choice.choice_text}}</label>
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-success btn-lg mt-4" value="Vote" />
</form>
{% endblock %}

Polling2/pollster/templates/polls/index.html
{% extends 'base.html'%}

{% block title %}
POLLS
{% endblock %}

{% block content %}
<h1 class="text-center mb-3">Poll Questions</h1>
{% if latest_question_list%}
{% for question in latest_question_list %}
<div class="card mb-3">
    <div class="card-body">
        <p class="lead">{{question.question_text}}</p>
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
        <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
    </div>
</div>
{% endfor %}
{% else %}
<p>No Questions</p>
{% endif %}
{% endblock %}

Polling2/pollster/templates/polls/results.html
{% extends 'base.html' %}
{% block title %}
Results
{% endblock %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge bg-success float-end">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>
<br>
<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back to Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">vote again</a>
{% endblock %}